import type {
  Agency,
  Asset,
  Carrier,
  CarrierAgencyLink,
  CategoryAgencyLink,
  Claim,
  Communication,
  CustomerProfile,
  Deposit,
  Document,
  InsuranceCategory,
  MarketingCampaign,
  MarketingMessage,
  Note,
  Payment,
  Policy,
  Prospect,
  QuoteRequest,
  Renewal,
  StatusEvent,
  User,
} from "@/types";

// Deterministic ids so cross references work in the seed.
const id = (s: string) => s;
const now = (offsetDays = 0) =>
  new Date(Date.now() - offsetDays * 24 * 60 * 60 * 1000).toISOString();

export const SEED_AGENCIES: Agency[] = [
  {
    id: id("agency_palmcoast"),
    name: "Palm Coast Private Client",
    logoUrl: "",
    brandColor: "#0d0c09",
    contactEmail: "hello@palmcoastpc.example",
    phone: "+1 (555) 312-0099",
    address: "210 Ocean Blvd, Palm Beach, FL 33480",
    website: "palmcoastpc.example",
    serviceAreas: ["FL", "GA", "SC"],
    tier: "mid",
    active: true,
    allowedUsers: 10,
    allowedProspectsPerMonth: 1000,
    allowedAiMessagesPerMonth: 5000,
    allowedCarriers: 12,
    createdAt: now(120),
  },
  {
    id: id("agency_lakeshore"),
    name: "Lakeshore High-Net-Worth Group",
    logoUrl: "",
    brandColor: "#3f3b30",
    contactEmail: "concierge@lakeshorehnw.example",
    phone: "+1 (555) 882-1100",
    address: "88 N Michigan Ave, Chicago, IL 60601",
    website: "lakeshorehnw.example",
    serviceAreas: ["IL", "WI", "IN", "MI"],
    tier: "ultra",
    active: true,
    allowedUsers: 999,
    allowedProspectsPerMonth: 99999,
    allowedAiMessagesPerMonth: 99999,
    allowedCarriers: 999,
    createdAt: now(300),
  },
];

export const SEED_USERS: User[] = [
  {
    id: id("user_master"),
    tenantId: null,
    role: "master_admin",
    email: "founder@quotex.example",
    name: "Quotex Founder",
    active: true,
    createdAt: now(365),
  },
  {
    id: id("user_agent_pc"),
    tenantId: "agency_palmcoast",
    role: "agent",
    email: "agent@palmcoastpc.example",
    username: "agent01-palmcoastpc",
    generatedPassword: "amber-falcon-3917",
    passwordUpdatedAt: now(200),
    name: "Olivia Marsh",
    phone: "+1 (555) 312-0011",
    profileCompleted: true,
    active: true,
    createdAt: now(200),
  },
  {
    id: id("user_manager_pc"),
    tenantId: "agency_palmcoast",
    role: "manager",
    email: "manager@palmcoastpc.example",
    username: "manager01-palmcoastpc",
    generatedPassword: "cedar-marlin-2104",
    passwordUpdatedAt: now(200),
    name: "Daniel Reyes",
    profileCompleted: true,
    active: true,
    createdAt: now(200),
  },
  {
    id: id("user_agent_ls"),
    tenantId: "agency_lakeshore",
    role: "agent",
    email: "agent@lakeshorehnw.example",
    username: "agent01-lakeshorehnw",
    generatedPassword: "ivory-regatta-7286",
    passwordUpdatedAt: now(180),
    name: "Henry Caldwell",
    profileCompleted: true,
    active: true,
    createdAt: now(180),
  },
  {
    id: id("user_customer_demo"),
    tenantId: "agency_palmcoast",
    role: "customer",
    email: "customer@demo.example",
    name: "Alexandra Whitford",
    phone: "+1 (555) 902-0431",
    active: true,
    createdAt: now(90),
  },
];

export const SEED_CUSTOMERS: CustomerProfile[] = [
  {
    id: id("customer_demo"),
    tenantId: "agency_palmcoast",
    userId: "user_customer_demo",
    name: "Alexandra Whitford",
    email: "customer@demo.example",
    phone: "+1 (555) 902-0431",
    mailingAddress: "44 Sea Breeze Ln, Palm Beach, FL 33480",
    garagingAddress: "44 Sea Breeze Ln, Palm Beach, FL 33480",
    additionalContacts: [
      { name: "Marcus Whitford", relation: "Spouse", phone: "+1 (555) 902-7711" },
    ],
    marketingOptInEmail: true,
    marketingOptInSms: true,
    // Demo seed: this client is owned by the Palm Coast agent so
    // the agent-portal demo isn't empty. Agents only see clients
    // their manager has assigned to them; managers see everyone.
    assignedAgentId: "user_agent_pc",
    createdAt: now(90),
  },
];

// Common state lists, factored so 30 carriers stay readable below.
const ALL_50 = [
  "AL","AK","AZ","AR","CA","CO","CT","DE","DC","FL","GA","HI","ID","IL","IN","IA",
  "KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM",
  "NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA",
  "WV","WI","WY",
];
const COASTAL_STATES = ["FL","GA","SC","NC","VA","MD","DE","NJ","NY","CT","RI","MA","NH","ME","TX","LA","MS","AL","CA","OR","WA","HI"];
const HNW_HUB_STATES = ["FL","GA","SC","NC","NY","CT","NJ","MA","PA","CA","WA","IL","TX","CO","AZ"];

// =====================================================================
// Top 30 private-client / personal-lines carriers used across the
// platform's seeded agencies. Mix of HNW specialists (Chubb, PURE,
// AIG PCS, Vault, Cincinnati HOME, Berkley One, Crestbrook, Hagerty,
// Markel, National General) and standard-market carriers commonly
// written by independent agencies (Travelers, Liberty, Safeco, etc.).
//
// `appetites[]` powers the ballpark estimator. Each row says:
// "for this asset type, here's the value band I'll write, the risk
// levels I accept, and how my pricing tends to position vs market."
// Tendency convention: 1.0 = at market, <1 = cheaper, >1 = pricier.
// Numbers are illustrative for the demo, NOT carrier-confidential.
// =====================================================================

export const SEED_CARRIERS: Carrier[] = [
  // ---- HNW specialists ------------------------------------------------
  {
    id: id("carrier_chubb"),
    name: "Chubb Masterpiece",
    claimsUrl: "https://www.chubb.com/us-en/claims.html",
    agentPortalUrl: "https://www.chubb.com/us-en/agents-brokers.html",
    appetiteNotes: "Coastal homes $1.5M+, high-value autos, fine art, jewelry. Strong in FL/NY/CA.",
    tendencyNotes: "Premium pricing, generous limits, white-glove claims. Slower to bind.",
    underwritingRules: "Wind mitigation required for coastal FL. 4-point inspection on homes 30+ yrs. Appraisals <3y for scheduled items.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "jewelry", "yacht", "umbrella_liability"],
    restrictedRisks: ["short-term rentals", "homes within 500 ft of coast without mitigation"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      minValue: 1_500_000,  riskLevels: ["low","medium","high"], pricingTendency: 1.15 },
      { assetType: "luxury_vehicle",    minValue: 100_000,    riskLevels: ["low","medium"],         pricingTendency: 1.10 },
      { assetType: "jewelry",           minValue: 25_000,     riskLevels: ["low","medium","high"], pricingTendency: 1.10 },
      { assetType: "yacht",             minValue: 500_000,    riskLevels: ["low","medium"],         pricingTendency: 1.12 },
      { assetType: "umbrella_liability", minValue: 1_000_000, riskLevels: ["low","medium","high"], pricingTendency: 1.05 },
      { assetType: "full_portfolio",    minValue: 5_000_000,  riskLevels: ["low","medium"],         pricingTendency: 1.12 },
    ],
    status: "active",
    createdAt: now(400),
  },
  {
    id: id("carrier_pure"),
    name: "PURE Insurance",
    claimsUrl: "https://www.pureinsurance.com/claims",
    appetiteNotes: "Membership-based reciprocal. HNW homes, yachts, umbrella.",
    tendencyNotes: "Aggressive on retention, white-glove claims, ~5–10% under Chubb.",
    underwritingRules: "Membership initiation fee. Yacht: captain credentials required for >50ft.",
    preferredAssetTypes: ["coastal_home", "yacht", "umbrella_liability", "luxury_vehicle"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      minValue: 1_000_000, riskLevels: ["low","medium"],         pricingTendency: 1.05 },
      { assetType: "luxury_vehicle",    minValue: 75_000,    riskLevels: ["low","medium"],         pricingTendency: 1.00 },
      { assetType: "yacht",             minValue: 250_000,   riskLevels: ["low","medium"],         pricingTendency: 1.02 },
      { assetType: "umbrella_liability", minValue: 1_000_000, riskLevels: ["low","medium","high"], pricingTendency: 0.98 },
      { assetType: "jewelry",           minValue: 25_000,    riskLevels: ["low","medium","high"], pricingTendency: 1.05 },
    ],
    status: "active",
    createdAt: now(380),
  },
  {
    id: id("carrier_aig"),
    name: "AIG Private Client Select",
    claimsUrl: "https://www.aig.com/private-client-group/claims",
    agentPortalUrl: "https://www.aig.com/business/insurance/login",
    appetiteNotes: "Ultra-high-net-worth full portfolio, fine art, jewelry collections.",
    tendencyNotes: "Strong on collections and complex risks; pricing similar to Chubb.",
    underwritingRules: "Schedule items >$50k. Appraisals within 3 years.",
    preferredAssetTypes: ["full_portfolio", "jewelry", "coastal_home", "yacht"],
    stateAvailability: HNW_HUB_STATES,
    appetites: [
      { assetType: "coastal_home",      minValue: 2_000_000, riskLevels: ["low","medium","high"], pricingTendency: 1.12 },
      { assetType: "jewelry",           minValue: 50_000,    riskLevels: ["low","medium","high"], pricingTendency: 1.08 },
      { assetType: "yacht",             minValue: 1_000_000, riskLevels: ["low","medium"],         pricingTendency: 1.10 },
      { assetType: "full_portfolio",    minValue: 10_000_000, riskLevels: ["low","medium"],        pricingTendency: 1.10 },
      { assetType: "umbrella_liability", minValue: 5_000_000, riskLevels: ["low","medium","high"], pricingTendency: 1.05 },
    ],
    status: "active",
    createdAt: now(370),
  },
  {
    id: id("carrier_cincinnati_home"),
    name: "Cincinnati Insurance (HOME)",
    claimsUrl: "https://www.cinfin.com/claims",
    appetiteNotes: "HNW home + auto package. Independent-agent channel only.",
    tendencyNotes: "Mid-market pricing, strong agent service.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "jewelry", "umbrella_liability"],
    stateAvailability: ["AL","AZ","AR","CO","CT","DC","DE","FL","GA","ID","IL","IN","IA","KS","KY","MD","MI","MN","MO","MT","NE","NH","NJ","NM","NY","NC","OH","OK","OR","PA","SC","TN","TX","UT","VA","WA","WV","WI","WY"],
    appetites: [
      { assetType: "coastal_home",      minValue: 500_000,   maxValue: 5_000_000, riskLevels: ["low","medium"], pricingTendency: 0.95 },
      { assetType: "luxury_vehicle",    minValue: 50_000,    maxValue: 250_000,   riskLevels: ["low","medium"], pricingTendency: 0.92 },
      { assetType: "umbrella_liability", minValue: 1_000_000, maxValue: 10_000_000, riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
    ],
    status: "active",
    createdAt: now(360),
  },
  {
    id: id("carrier_vault"),
    name: "Vault Insurance",
    claimsUrl: "https://www.vault.insurance/claims",
    appetiteNotes: "HNW home, yacht, umbrella. Strong in FL coastal corridor.",
    tendencyNotes: "Competitive HNW pricing — typically below Chubb/PURE.",
    preferredAssetTypes: ["coastal_home", "yacht", "umbrella_liability", "luxury_vehicle"],
    stateAvailability: ["FL","GA","SC","NC","NY","NJ","CT","CA","TX","AZ"],
    appetites: [
      { assetType: "coastal_home",      minValue: 1_000_000, riskLevels: ["low","medium"],         pricingTendency: 1.00 },
      { assetType: "yacht",             minValue: 250_000,   riskLevels: ["low","medium"],         pricingTendency: 0.98 },
      { assetType: "umbrella_liability", minValue: 1_000_000, riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
      { assetType: "luxury_vehicle",    minValue: 75_000,    riskLevels: ["low","medium"],         pricingTendency: 0.98 },
    ],
    status: "active",
    createdAt: now(350),
  },
  {
    id: id("carrier_berkley_one"),
    name: "Berkley One",
    claimsUrl: "https://www.berkleyone.com/claims",
    appetiteNotes: "HNW home, valuables, auto. W. R. Berkley's HNW arm.",
    tendencyNotes: "Mid-to-premium pricing.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "jewelry", "umbrella_liability"],
    stateAvailability: HNW_HUB_STATES,
    appetites: [
      { assetType: "coastal_home",      minValue: 1_000_000, riskLevels: ["low","medium"],         pricingTendency: 1.05 },
      { assetType: "jewelry",           minValue: 25_000,    riskLevels: ["low","medium"],         pricingTendency: 1.05 },
      { assetType: "luxury_vehicle",    minValue: 75_000,    riskLevels: ["low","medium"],         pricingTendency: 1.02 },
      { assetType: "umbrella_liability", minValue: 1_000_000, riskLevels: ["low","medium","high"], pricingTendency: 1.00 },
    ],
    status: "active",
    createdAt: now(340),
  },
  {
    id: id("carrier_crestbrook"),
    name: "Crestbrook (Nationwide Private Client)",
    claimsUrl: "https://www.nationwide.com/personal/insurance/private-client",
    appetiteNotes: "HNW home + auto + valuables, Nationwide-backed.",
    tendencyNotes: "Mid-market pricing, broad availability.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "jewelry", "umbrella_liability"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      minValue: 750_000,   maxValue: 10_000_000, riskLevels: ["low","medium"], pricingTendency: 1.00 },
      { assetType: "luxury_vehicle",    minValue: 50_000,    riskLevels: ["low","medium"],         pricingTendency: 0.98 },
      { assetType: "jewelry",           minValue: 25_000,    riskLevels: ["low","medium","high"], pricingTendency: 1.00 },
      { assetType: "umbrella_liability", minValue: 1_000_000, riskLevels: ["low","medium","high"], pricingTendency: 0.98 },
    ],
    status: "active",
    createdAt: now(330),
  },
  {
    id: id("carrier_hagerty"),
    name: "Hagerty",
    claimsUrl: "https://www.hagerty.com/services/claims",
    appetiteNotes: "Collector vehicles + vintage boats. Agreed-value specialists.",
    tendencyNotes: "Dramatically below standard auto market for properly stored collector cars.",
    preferredAssetTypes: ["luxury_vehicle", "yacht"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "luxury_vehicle",    minValue: 25_000,    riskLevels: ["low"],                  pricingTendency: 0.55 },
      { assetType: "yacht",             minValue: 50_000,    maxValue: 1_000_000, riskLevels: ["low","medium"], pricingTendency: 0.85 },
    ],
    status: "active",
    createdAt: now(320),
  },
  {
    id: id("carrier_markel"),
    name: "Markel Specialty",
    claimsUrl: "https://www.markel.com/claims",
    appetiteNotes: "Yachts, collector autos, scheduled jewelry, specialty fine art.",
    tendencyNotes: "Sharp pricing on specialty, slower on home/auto.",
    preferredAssetTypes: ["yacht", "luxury_vehicle", "jewelry"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "yacht",             minValue: 100_000,   riskLevels: ["low","medium","high"], pricingTendency: 0.92 },
      { assetType: "luxury_vehicle",    minValue: 75_000,    riskLevels: ["low","medium"],         pricingTendency: 0.95 },
      { assetType: "jewelry",           minValue: 50_000,    riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
    ],
    status: "active",
    createdAt: now(310),
  },
  {
    id: id("carrier_natgen_premier"),
    name: "National General Premier",
    claimsUrl: "https://www.nationalgeneral.com/claims",
    appetiteNotes: "Allstate-owned HNW home + auto package.",
    tendencyNotes: "Mid-market pricing, broad availability.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "umbrella_liability"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      minValue: 500_000,   maxValue: 5_000_000, riskLevels: ["low","medium"], pricingTendency: 1.00 },
      { assetType: "luxury_vehicle",    minValue: 50_000,    riskLevels: ["low","medium"],         pricingTendency: 1.00 },
      { assetType: "umbrella_liability", minValue: 1_000_000, riskLevels: ["low","medium","high"], pricingTendency: 1.00 },
    ],
    status: "active",
    createdAt: now(300),
  },
  // ---- Standard-market personal lines --------------------------------
  {
    id: id("carrier_travelers"),
    name: "Travelers",
    claimsUrl: "https://www.travelers.com/claims",
    agentPortalUrl: "https://www.travelers.com/agents/login",
    appetiteNotes: "Home, auto, umbrella. Broad-market personal lines.",
    tendencyNotes: "At-market pricing across most lines.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "umbrella_liability", "jewelry"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      maxValue: 2_500_000, riskLevels: ["low","medium"],         pricingTendency: 1.00 },
      { assetType: "luxury_vehicle",    maxValue: 150_000,   riskLevels: ["low","medium","high"], pricingTendency: 1.00 },
      { assetType: "umbrella_liability", minValue: 1_000_000, maxValue: 10_000_000, riskLevels: ["low","medium","high"], pricingTendency: 1.00 },
      { assetType: "jewelry",           maxValue: 100_000,   riskLevels: ["low","medium"],         pricingTendency: 1.05 },
    ],
    status: "active",
    createdAt: now(295),
  },
  {
    id: id("carrier_liberty"),
    name: "Liberty Mutual",
    claimsUrl: "https://www.libertymutual.com/customer-support/claims",
    agentPortalUrl: "https://business.libertymutual.com",
    appetiteNotes: "Personal home + auto. Direct + agent channels.",
    tendencyNotes: "Slightly above market in NE/CA.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "umbrella_liability"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      maxValue: 2_000_000, riskLevels: ["low","medium","high"], pricingTendency: 1.05 },
      { assetType: "luxury_vehicle",    maxValue: 125_000,   riskLevels: ["low","medium","high"], pricingTendency: 1.05 },
      { assetType: "umbrella_liability", maxValue: 5_000_000, riskLevels: ["low","medium","high"], pricingTendency: 1.02 },
    ],
    status: "active",
    createdAt: now(290),
  },
  {
    id: id("carrier_safeco"),
    name: "Safeco (Liberty Mutual)",
    claimsUrl: "https://www.safeco.com/claims",
    appetiteNotes: "Liberty's independent-agent brand. Home, auto.",
    tendencyNotes: "Competitive on bundled home + auto.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "umbrella_liability"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium"],         pricingTendency: 0.95 },
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium"],         pricingTendency: 0.95 },
      { assetType: "umbrella_liability", maxValue: 5_000_000, riskLevels: ["low","medium"],        pricingTendency: 0.97 },
    ],
    status: "active",
    createdAt: now(285),
  },
  {
    id: id("carrier_hartford"),
    name: "The Hartford",
    claimsUrl: "https://www.thehartford.com/claims",
    appetiteNotes: "Home + auto, AARP affinity, umbrella.",
    tendencyNotes: "Slightly above market, strong claims service.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "umbrella_liability"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium"],         pricingTendency: 1.05 },
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium"],         pricingTendency: 1.03 },
      { assetType: "umbrella_liability", maxValue: 10_000_000, riskLevels: ["low","medium","high"], pricingTendency: 1.05 },
    ],
    status: "active",
    createdAt: now(280),
  },
  {
    id: id("carrier_nationwide"),
    name: "Nationwide",
    claimsUrl: "https://www.nationwide.com/claims",
    agentPortalUrl: "https://www.agentcenter.nationwide.com",
    appetiteNotes: "Personal lines (standard tier), jewelry rider, umbrella.",
    tendencyNotes: "Competitive across the standard market.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "jewelry", "umbrella_liability"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
      { assetType: "jewelry",           maxValue: 50_000,    riskLevels: ["low","medium"],         pricingTendency: 0.98 },
      { assetType: "umbrella_liability", maxValue: 5_000_000, riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
    ],
    status: "active",
    createdAt: now(275),
  },
  {
    id: id("carrier_progressive"),
    name: "Progressive",
    claimsUrl: "https://www.progressive.com/claims",
    agentPortalUrl: "https://progressivecommercial.com/agent-login/",
    appetiteNotes: "Auto-heavy. Home via partner programs.",
    tendencyNotes: "Aggressive on auto.",
    preferredAssetTypes: ["luxury_vehicle"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium","high"], pricingTendency: 0.90 },
    ],
    status: "active",
    createdAt: now(270),
  },
  {
    id: id("carrier_allstate"),
    name: "Allstate",
    claimsUrl: "https://www.allstate.com/claims",
    agentPortalUrl: "https://agents.allstate.com",
    appetiteNotes: "Home, auto, umbrella. Standard market.",
    tendencyNotes: "At-market pricing.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "umbrella_liability"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium","high"], pricingTendency: 1.00 },
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium","high"], pricingTendency: 1.00 },
      { assetType: "umbrella_liability", maxValue: 5_000_000, riskLevels: ["low","medium","high"], pricingTendency: 1.00 },
    ],
    status: "active",
    createdAt: now(265),
  },
  {
    id: id("carrier_farmers"),
    name: "Farmers",
    claimsUrl: "https://www.farmers.com/claims",
    agentPortalUrl: "https://agents.farmers.com",
    appetiteNotes: "Home, auto, umbrella, jewelry.",
    tendencyNotes: "Slightly above market on home.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "jewelry", "umbrella_liability"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium","high"], pricingTendency: 1.05 },
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium","high"], pricingTendency: 1.02 },
      { assetType: "jewelry",           maxValue: 50_000,    riskLevels: ["low","medium"],         pricingTendency: 1.05 },
      { assetType: "umbrella_liability", maxValue: 5_000_000, riskLevels: ["low","medium","high"], pricingTendency: 1.00 },
    ],
    status: "active",
    createdAt: now(260),
  },
  {
    id: id("carrier_statefarm"),
    name: "State Farm",
    claimsUrl: "https://www.statefarm.com/claims",
    agentPortalUrl: "https://b2b.statefarm.com",
    appetiteNotes: "Home, auto, jewelry rider. Captive agent channel.",
    tendencyNotes: "Competitive on bundled.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "jewelry", "umbrella_liability"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
      { assetType: "jewelry",           maxValue: 50_000,    riskLevels: ["low","medium"],         pricingTendency: 0.95 },
      { assetType: "umbrella_liability", maxValue: 5_000_000, riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
    ],
    status: "active",
    createdAt: now(255),
  },
  {
    id: id("carrier_usaa"),
    name: "USAA",
    claimsUrl: "https://www.usaa.com/claims",
    appetiteNotes: "Military + family. Home, auto, valuables, umbrella.",
    tendencyNotes: "Below market for eligible members.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "jewelry", "umbrella_liability"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      maxValue: 2_000_000, riskLevels: ["low","medium","high"], pricingTendency: 0.85 },
      { assetType: "luxury_vehicle",    maxValue: 150_000,   riskLevels: ["low","medium","high"], pricingTendency: 0.85 },
      { assetType: "jewelry",           maxValue: 75_000,    riskLevels: ["low","medium"],         pricingTendency: 0.88 },
      { assetType: "umbrella_liability", maxValue: 5_000_000, riskLevels: ["low","medium","high"], pricingTendency: 0.88 },
    ],
    status: "active",
    createdAt: now(250),
  },
  {
    id: id("carrier_autoowners"),
    name: "Auto-Owners Insurance",
    claimsUrl: "https://www.auto-owners.com/claims",
    appetiteNotes: "Regional Midwest/SE. Home, auto, umbrella.",
    tendencyNotes: "Competitive in MI/OH/TN.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "umbrella_liability"],
    stateAvailability: ["AL","AZ","AR","CO","FL","GA","ID","IL","IN","IA","KS","KY","MI","MN","MO","NE","NC","ND","OH","PA","SC","SD","TN","UT","VA","WI"],
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium"],         pricingTendency: 0.95 },
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium"],         pricingTendency: 0.93 },
      { assetType: "umbrella_liability", maxValue: 5_000_000, riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
    ],
    status: "active",
    createdAt: now(245),
  },
  {
    id: id("carrier_erie"),
    name: "Erie Insurance",
    claimsUrl: "https://www.erieinsurance.com/claims",
    appetiteNotes: "Regional NE/MidAtlantic. Home, auto, umbrella.",
    tendencyNotes: "Aggressive in PA/OH/VA.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "umbrella_liability"],
    stateAvailability: ["DC","IL","IN","KY","MD","NY","NC","OH","PA","TN","VA","WV","WI"],
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium"],         pricingTendency: 0.90 },
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium"],         pricingTendency: 0.88 },
      { assetType: "umbrella_liability", maxValue: 5_000_000, riskLevels: ["low","medium","high"], pricingTendency: 0.92 },
    ],
    status: "active",
    createdAt: now(240),
  },
  {
    id: id("carrier_mercury"),
    name: "Mercury Insurance",
    claimsUrl: "https://www.mercuryinsurance.com/claims",
    appetiteNotes: "CA-heavy. Auto + home.",
    tendencyNotes: "Below market in CA, NV, AZ.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle"],
    stateAvailability: ["AZ","CA","FL","GA","IL","NV","NJ","NY","OK","TX","VA"],
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium"],         pricingTendency: 0.88 },
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium","high"], pricingTendency: 0.85 },
    ],
    status: "active",
    createdAt: now(235),
  },
  {
    id: id("carrier_amfam"),
    name: "American Family",
    claimsUrl: "https://www.amfam.com/claims",
    appetiteNotes: "Midwest. Home, auto, umbrella.",
    tendencyNotes: "Mid-market.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "umbrella_liability"],
    stateAvailability: ["AZ","CO","GA","ID","IL","IN","IA","KS","KY","MN","MO","NE","NV","ND","OH","OR","SD","TN","UT","WA","WI"],
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
      { assetType: "umbrella_liability", maxValue: 5_000_000, riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
    ],
    status: "active",
    createdAt: now(230),
  },
  {
    id: id("carrier_foremost"),
    name: "Foremost (Farmers Specialty)",
    claimsUrl: "https://www.foremost.com/claims",
    appetiteNotes: "Specialty: manufactured home, motorcycle, off-road, vacant home.",
    tendencyNotes: "At-market for specialty risks others won't write.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      maxValue: 750_000, riskLevels: ["medium","high"],         pricingTendency: 1.05 },
      { assetType: "luxury_vehicle",    maxValue: 75_000,  riskLevels: ["medium","high"],         pricingTendency: 1.00 },
    ],
    status: "active",
    createdAt: now(225),
  },
  {
    id: id("carrier_stillwater"),
    name: "Stillwater Insurance",
    claimsUrl: "https://www.stillwater.com/claims",
    appetiteNotes: "Coastal FL specialty home + condo.",
    tendencyNotes: "Premium on FL coast, accepts wind exposure.",
    preferredAssetTypes: ["coastal_home"],
    stateAvailability: ["FL","GA","SC","NC","LA","MS","AL","TX"],
    appetites: [
      { assetType: "coastal_home",      maxValue: 2_000_000, riskLevels: ["medium","high"],       pricingTendency: 1.10 },
    ],
    status: "active",
    createdAt: now(220),
  },
  {
    id: id("carrier_plymouth_rock"),
    name: "Plymouth Rock Assurance",
    claimsUrl: "https://www.plymouthrock.com/claims",
    appetiteNotes: "NE coastal home + auto (NJ, MA, NY, CT, NH, PA).",
    tendencyNotes: "Premium on coastal, competitive inland.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle"],
    stateAvailability: ["CT","MA","NH","NJ","NY","PA"],
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium","high"], pricingTendency: 1.05 },
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium","high"], pricingTendency: 1.00 },
    ],
    status: "active",
    createdAt: now(215),
  },
  {
    id: id("carrier_kemper"),
    name: "Kemper",
    claimsUrl: "https://www.kemper.com/claims",
    appetiteNotes: "Non-standard auto, specialty home.",
    tendencyNotes: "Above market on non-standard.",
    preferredAssetTypes: ["luxury_vehicle"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "luxury_vehicle",    maxValue: 75_000,    riskLevels: ["medium","high"],       pricingTendency: 1.10 },
    ],
    status: "active",
    createdAt: now(210),
  },
  {
    id: id("carrier_westfield"),
    name: "Westfield Insurance",
    claimsUrl: "https://www.westfieldinsurance.com/claims",
    appetiteNotes: "Midwest standard market. Home, auto, umbrella.",
    tendencyNotes: "Competitive in OH/IN/PA.",
    preferredAssetTypes: ["coastal_home", "luxury_vehicle", "umbrella_liability"],
    stateAvailability: ["DC","DE","IL","IN","IA","KY","MD","MI","MN","NJ","NC","OH","PA","TN","VA","WV"],
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium"],         pricingTendency: 0.95 },
      { assetType: "luxury_vehicle",    maxValue: 100_000,   riskLevels: ["low","medium"],         pricingTendency: 0.95 },
      { assetType: "umbrella_liability", maxValue: 5_000_000, riskLevels: ["low","medium","high"], pricingTendency: 0.95 },
    ],
    status: "active",
    createdAt: now(205),
  },
  {
    id: id("carrier_amtrust"),
    name: "AmTrust Financial",
    claimsUrl: "https://www.amtrustfinancial.com/claims",
    appetiteNotes: "Niche personal + small commercial.",
    tendencyNotes: "At-market for specialty.",
    preferredAssetTypes: ["coastal_home", "umbrella_liability"],
    stateAvailability: ALL_50,
    appetites: [
      { assetType: "coastal_home",      maxValue: 1_500_000, riskLevels: ["low","medium"],         pricingTendency: 1.00 },
      { assetType: "umbrella_liability", maxValue: 5_000_000, riskLevels: ["low","medium","high"], pricingTendency: 1.00 },
    ],
    status: "active",
    createdAt: now(200),
  },
];

// Each demo agency is linked to a representative mix of carriers
// so the estimator's appetite-matching has enough carriers to
// average across. Palm Coast leans HNW + coastal; Lakeshore leans
// midwest + standard market.
const PALMCOAST_CARRIERS = [
  "carrier_chubb", "carrier_pure", "carrier_aig", "carrier_cincinnati_home",
  "carrier_vault", "carrier_berkley_one", "carrier_crestbrook", "carrier_hagerty",
  "carrier_markel", "carrier_natgen_premier", "carrier_travelers", "carrier_liberty",
  "carrier_safeco", "carrier_hartford", "carrier_nationwide", "carrier_progressive",
  "carrier_allstate", "carrier_farmers", "carrier_statefarm", "carrier_stillwater",
  "carrier_plymouth_rock",
];
const LAKESHORE_CARRIERS = [
  "carrier_chubb", "carrier_pure", "carrier_aig", "carrier_cincinnati_home",
  "carrier_berkley_one", "carrier_crestbrook", "carrier_hagerty", "carrier_markel",
  "carrier_natgen_premier", "carrier_travelers", "carrier_liberty", "carrier_safeco",
  "carrier_hartford", "carrier_nationwide", "carrier_progressive", "carrier_allstate",
  "carrier_farmers", "carrier_statefarm", "carrier_usaa", "carrier_autoowners",
  "carrier_erie", "carrier_amfam", "carrier_foremost", "carrier_kemper",
  "carrier_westfield", "carrier_amtrust",
];

export const SEED_CARRIER_LINKS: CarrierAgencyLink[] = [
  ...PALMCOAST_CARRIERS.map((cid) => ({
    id: id(`link_pc_${cid}`),
    tenantId: "agency_palmcoast",
    carrierId: cid,
    active: true,
    createdAt: now(120),
  })),
  ...LAKESHORE_CARRIERS.map((cid) => ({
    id: id(`link_ls_${cid}`),
    tenantId: "agency_lakeshore",
    carrierId: cid,
    active: true,
    createdAt: now(300),
  })),
];

export const SEED_ASSETS: Asset[] = [
  {
    id: id("asset_home"),
    tenantId: "agency_palmcoast",
    customerId: "customer_demo",
    type: "coastal_home",
    label: "Sea Breeze Estate",
    estimatedValue: 4_250_000,
    status: "insured",
    details: {
      address: "44 Sea Breeze Ln, Palm Beach, FL 33480",
      squareFootage: 6800,
      roofAge: 4,
      windMitigation: true,
      floodZone: "AE",
      constructionType: "Concrete block",
    },
    createdAt: now(80),
  },
  {
    id: id("asset_vehicle"),
    tenantId: "agency_palmcoast",
    customerId: "customer_demo",
    type: "luxury_vehicle",
    label: "2023 Porsche 911 Turbo S",
    estimatedValue: 245_000,
    status: "insured",
    details: {
      vin: "WP0AD2A99NS260123",
      year: 2023,
      make: "Porsche",
      model: "911 Turbo S",
      garagingAddress: "44 Sea Breeze Ln, Palm Beach, FL 33480",
      usage: "Pleasure",
      drivers: [{ name: "Alexandra Whitford", license: "FL" }],
    },
    createdAt: now(70),
  },
  {
    id: id("asset_yacht"),
    tenantId: "agency_palmcoast",
    customerId: "customer_demo",
    type: "yacht",
    label: "M/Y Liora — 72ft",
    estimatedValue: 3_100_000,
    status: "pending",
    details: {
      length: 72,
      year: 2021,
      make: "Princess Yachts",
      model: "Y72",
      marinaLocation: "Palm Harbor Marina, Palm Beach, FL",
      navigationArea: "FL coastal + Bahamas",
      operator: "captain",
    },
    createdAt: now(20),
  },
];

export const SEED_POLICIES: Policy[] = [
  {
    id: id("policy_home"),
    tenantId: "agency_palmcoast",
    customerId: "customer_demo",
    assetId: "asset_home",
    carrierId: "carrier_chubb",
    policyNumber: "CHB-HM-558920",
    premiumEstimate: 18_400,
    finalPremium: 17_950,
    effectiveDate: now(60),
    renewalDate: now(-305),
    status: "bound",
    renewalStatus: "upcoming",
    agentId: "user_agent_pc",
    paymentFrequency: "quarterly",
    coverages: [
      { name: "Dwelling (Coverage A)", limit: 2_400_000, deductible: 5_000, description: "Replacement cost on the structure." },
      { name: "Other Structures (Coverage B)", limit: 240_000, description: "Detached structures (guest house, garage)." },
      { name: "Personal Property (Coverage C)", limit: 1_200_000, deductible: 5_000, description: "Furniture, electronics, scheduled jewelry rides separately." },
      { name: "Loss of Use (Coverage D)", limit: 480_000, description: "Additional living expense if uninhabitable." },
      { name: "Personal Liability (Coverage E)", limit: 1_000_000 },
      { name: "Medical Payments (Coverage F)", limit: 10_000 },
      { name: "Hurricane / Named-Storm Deductible", deductible: 36_000, description: "1.5% of Coverage A." },
    ],
    endorsements: [
      { name: "Water Backup Coverage", description: "$25,000 limit. Backup of sewers and drains.", addedAt: now(70) },
      { name: "Equipment Breakdown", description: "Generator, HVAC, smart-home systems.", addedAt: now(70) },
      { name: "Service Line Coverage", description: "Underground utility lines from street to home.", addedAt: now(40) },
    ],
    exclusions: [
      "Flood (separate NFIP / private flood policy required)",
      "Earth movement / sinkhole (FL endorsement available)",
      "Wear and tear, mechanical breakdown beyond Equipment Breakdown endorsement",
      "Intentional acts",
    ],
    additionalInsureds: [
      { name: "Marcus Whitford", relationship: "Spouse — Additional Insured" },
    ],
    premiumBreakdown: { base: 16_800, fees: 350, taxes: 800, total: 17_950 },
    nextPaymentDueDate: now(-30),
    nextPaymentAmount: 4_487,
    createdAt: now(75),
  },
  {
    id: id("policy_vehicle"),
    tenantId: "agency_palmcoast",
    customerId: "customer_demo",
    assetId: "asset_vehicle",
    carrierId: "carrier_pure",
    policyNumber: "PURE-AU-441188",
    premiumEstimate: 6_200,
    finalPremium: 6_050,
    effectiveDate: now(50),
    renewalDate: now(-315),
    status: "bound",
    renewalStatus: "not_due",
    agentId: "user_agent_pc",
    paymentFrequency: "semi_annual",
    coverages: [
      { name: "Bodily Injury Liability", limit: 500_000, description: "Per person / per accident." },
      { name: "Property Damage Liability", limit: 250_000 },
      { name: "Comprehensive", deductible: 1_000, description: "Theft, vandalism, glass, weather." },
      { name: "Collision", deductible: 1_000 },
      { name: "Uninsured / Underinsured Motorist", limit: 500_000 },
      { name: "Medical Payments", limit: 25_000 },
      { name: "Rental Reimbursement", limit: 5_000, description: "$100/day, up to 50 days." },
      { name: "Roadside Assistance", description: "PURE concierge tow + lockout." },
    ],
    endorsements: [
      { name: "Agreed Value", description: "Settles at agreed value, not ACV. Important for collector / luxury vehicles.", addedAt: now(60) },
      { name: "OEM Parts", description: "Repairs use original-equipment manufacturer parts.", addedAt: now(60) },
    ],
    exclusions: [
      "Racing or track-day use",
      "Commercial use / ride-share",
      "Wear and tear / mechanical breakdown",
    ],
    additionalInsureds: [
      { name: "Marcus Whitford", relationship: "Spouse — Listed Driver" },
    ],
    premiumBreakdown: { base: 5_800, fees: 100, taxes: 150, total: 6_050 },
    nextPaymentDueDate: now(-45),
    nextPaymentAmount: 3_025,
    createdAt: now(65),
  },
];

export const SEED_QUOTE_REQUESTS: QuoteRequest[] = [
  {
    id: id("quote_yacht"),
    tenantId: "agency_palmcoast",
    customerId: "customer_demo",
    assetType: "yacht",
    rawDescription:
      "Looking to insure a 72ft Princess yacht based in Palm Beach. Bahamas cruising. Captain operated.",
    parsedData: {
      length: 72,
      year: 2021,
      make: "Princess Yachts",
      model: "Y72",
      marinaLocation: "Palm Harbor Marina, Palm Beach, FL",
      navigationArea: "FL coastal + Bahamas",
      operator: "captain",
      estimatedValue: 3_100_000,
    },
    aiPremiumEstimateMin: 28_500,
    aiPremiumEstimateMax: 34_000,
    aiRecommendedCarrierId: "carrier_pure",
    aiRecommendationReason:
      "PURE has strong appetite for $1M+ yachts with captain credentials. Coastal FL navigation aligns with appetite. Chubb is alternate.",
    missingDocuments: ["Captain credentials", "Most recent survey", "Marina contract"],
    status: "submitted_to_agent",
    assignedAgentId: "user_agent_pc",
    createdAt: now(20),
  },
];

export const SEED_DEPOSITS: Deposit[] = [
  {
    id: id("deposit_home"),
    tenantId: "agency_palmcoast",
    customerId: "customer_demo",
    policyId: "policy_home",
    amount: 2_500,
    currency: "USD",
    stripePaymentIntentId: "pi_seed_home",
    status: "paid",
    paidAt: now(74),
    createdAt: now(74),
  },
  {
    id: id("deposit_yacht"),
    tenantId: "agency_palmcoast",
    customerId: "customer_demo",
    quoteRequestId: "quote_yacht",
    amount: 1_000,
    currency: "USD",
    stripePaymentIntentId: "pi_seed_yacht",
    status: "paid",
    paidAt: now(18),
    createdAt: now(18),
  },
];

export const SEED_PAYMENTS: Payment[] = [
  {
    id: id("payment_home_1"),
    tenantId: "agency_palmcoast",
    customerId: "customer_demo",
    policyId: "policy_home",
    amount: 4_487,
    currency: "USD",
    method: "card",
    status: "paid",
    paidAt: now(60),
    createdAt: now(60),
  },
  {
    id: id("payment_home_2"),
    tenantId: "agency_palmcoast",
    customerId: "customer_demo",
    policyId: "policy_home",
    amount: 4_487,
    currency: "USD",
    method: "card",
    status: "paid",
    paidAt: now(30),
    createdAt: now(30),
  },
];

export const SEED_PROSPECTS: Prospect[] = [
  {
    id: id("prospect_jenkins"),
    tenantId: "agency_palmcoast",
    name: "Robert Jenkins",
    email: "rjenkins@example.com",
    phone: "+1 (555) 220-7711",
    assetType: "coastal_home",
    estimatedValue: 2_750_000,
    aiSummary:
      "Started a coastal home quote on a $2.75M FL property. Uploaded one photo, did not complete wind mitigation. Stopped at document upload step.",
    lastAction: "Abandoned at document upload step",
    lastActivityAt: now(3),
    recommendedFollowUp:
      "Personal email offering to schedule a 15-min call to walk through wind mitigation requirements; mention Chubb appetite.",
    marketingStatus: "active",
    assignedAgentId: "user_agent_pc",
    status: "abandoned",
    createdAt: now(5),
  },
  {
    id: id("prospect_carmichael"),
    tenantId: "agency_palmcoast",
    name: "Eleanor Carmichael",
    email: "eleanor.c@example.com",
    phone: "+1 (555) 880-9921",
    assetType: "jewelry",
    estimatedValue: 480_000,
    aiSummary:
      "Inquired about scheduling jewelry collection. Has appraisals on hand. Did not complete intake.",
    lastAction: "Viewed jewelry intake form",
    lastActivityAt: now(12),
    recommendedFollowUp:
      "SMS: short reminder with link to resume. Offer concierge appraisal review.",
    marketingStatus: "active",
    status: "nurturing",
    createdAt: now(15),
  },
  {
    id: id("prospect_lin"),
    tenantId: "agency_lakeshore",
    name: "Henry Lin",
    email: "henry.lin@example.com",
    assetType: "full_portfolio",
    estimatedValue: 12_000_000,
    aiSummary: "Inquired about full portfolio coverage. Owns 2 homes, art collection, and yacht.",
    lastAction: "Submitted contact form",
    lastActivityAt: now(2),
    recommendedFollowUp: "Manager call within 24h.",
    marketingStatus: "active",
    status: "new",
    createdAt: now(2),
  },
];

export const SEED_DOCUMENTS: Document[] = [
  // Home policy documents
  {
    id: id("doc_home_dec"),
    tenantId: "agency_palmcoast",
    uploadedById: "user_agent_pc",
    fileName: "Whitford-Chubb-Masterpiece-Declarations.pdf",
    fileType: "application/pdf",
    type: "declarations_page",
    visibility: "customer_visible",
    status: "approved",
    storagePath: "s3://placeholder/agency_palmcoast/policy_home/declarations.pdf",
    policyId: "policy_home",
    customerId: "customer_demo",
    assetId: "asset_home",
    needsRenewalUpdate: true,
    renewalForRenewalId: "ren_home",
    uploadedAt: now(60),
  },
  {
    id: id("doc_home_booklet"),
    tenantId: "agency_palmcoast",
    uploadedById: "user_agent_pc",
    fileName: "Chubb-Masterpiece-Homeowners-Booklet.pdf",
    fileType: "application/pdf",
    type: "policy_booklet",
    visibility: "customer_visible",
    status: "approved",
    storagePath: "s3://placeholder/agency_palmcoast/policy_home/booklet.pdf",
    policyId: "policy_home",
    customerId: "customer_demo",
    assetId: "asset_home",
    uploadedAt: now(60),
  },
  {
    id: id("doc_home_endorse"),
    tenantId: "agency_palmcoast",
    uploadedById: "user_agent_pc",
    fileName: "Endorsement-ServiceLine-Added.pdf",
    fileType: "application/pdf",
    type: "endorsement_document",
    visibility: "customer_visible",
    status: "approved",
    storagePath: "s3://placeholder/agency_palmcoast/policy_home/service_line.pdf",
    policyId: "policy_home",
    customerId: "customer_demo",
    assetId: "asset_home",
    needsRenewalUpdate: true,
    renewalForRenewalId: "ren_home",
    uploadedAt: now(40),
  },
  {
    id: id("doc_home_poi"),
    tenantId: "agency_palmcoast",
    uploadedById: "user_agent_pc",
    fileName: "PalmBeach-POI-Chubb.pdf",
    fileType: "application/pdf",
    type: "proof_of_insurance",
    visibility: "customer_visible",
    status: "approved",
    storagePath: "s3://placeholder/agency_palmcoast/policy_home/poi.pdf",
    policyId: "policy_home",
    customerId: "customer_demo",
    assetId: "asset_home",
    needsRenewalUpdate: true,
    renewalForRenewalId: "ren_home",
    uploadedAt: now(60),
  },
  {
    id: id("doc_home_inspection"),
    tenantId: "agency_palmcoast",
    uploadedById: "user_agent_pc",
    fileName: "4-Point-Inspection-2024.pdf",
    fileType: "application/pdf",
    type: "inspection_report",
    visibility: "customer_visible",
    status: "approved",
    storagePath: "s3://placeholder/agency_palmcoast/policy_home/inspection.pdf",
    policyId: "policy_home",
    customerId: "customer_demo",
    assetId: "asset_home",
    uploadedAt: now(78),
  },
  {
    id: id("doc_home_appraisal"),
    tenantId: "agency_palmcoast",
    uploadedById: "user_customer_demo",
    fileName: "Whitford-Home-Appraisal-2024.pdf",
    fileType: "application/pdf",
    type: "appraisal",
    visibility: "customer_visible",
    status: "approved",
    storagePath: "s3://placeholder/agency_palmcoast/policy_home/appraisal.pdf",
    assetId: "asset_home",
    customerId: "customer_demo",
    uploadedAt: now(75),
  },
  // Auto policy documents
  {
    id: id("doc_auto_dec"),
    tenantId: "agency_palmcoast",
    uploadedById: "user_agent_pc",
    fileName: "Whitford-PURE-Auto-Declarations.pdf",
    fileType: "application/pdf",
    type: "declarations_page",
    visibility: "customer_visible",
    status: "approved",
    storagePath: "s3://placeholder/agency_palmcoast/policy_vehicle/declarations.pdf",
    policyId: "policy_vehicle",
    customerId: "customer_demo",
    assetId: "asset_vehicle",
    uploadedAt: now(50),
  },
  {
    id: id("doc_auto_idcard"),
    tenantId: "agency_palmcoast",
    uploadedById: "user_agent_pc",
    fileName: "Insurance-ID-Card-2024.pdf",
    fileType: "application/pdf",
    type: "insurance_id_card",
    visibility: "customer_visible",
    status: "approved",
    storagePath: "s3://placeholder/agency_palmcoast/policy_vehicle/idcard.pdf",
    policyId: "policy_vehicle",
    customerId: "customer_demo",
    assetId: "asset_vehicle",
    uploadedAt: now(50),
  },
  {
    id: id("doc_auto_booklet"),
    tenantId: "agency_palmcoast",
    uploadedById: "user_agent_pc",
    fileName: "PURE-Auto-Coverage-Forms.pdf",
    fileType: "application/pdf",
    type: "policy_booklet",
    visibility: "customer_visible",
    status: "approved",
    storagePath: "s3://placeholder/agency_palmcoast/policy_vehicle/booklet.pdf",
    policyId: "policy_vehicle",
    customerId: "customer_demo",
    assetId: "asset_vehicle",
    uploadedAt: now(50),
  },
];

export const SEED_STATUS: StatusEvent[] = [
  {
    id: id("se_1"),
    tenantId: "agency_palmcoast",
    source: "system",
    message: "Policy bound with Chubb",
    visibility: "customer_visible",
    policyId: "policy_home",
    customerId: "customer_demo",
    createdAt: now(60),
  },
  {
    id: id("se_2"),
    tenantId: "agency_palmcoast",
    source: "agent",
    message: "Submitted yacht file to PURE for underwriting review.",
    visibility: "customer_visible",
    customerId: "customer_demo",
    createdAt: now(15),
  },
  {
    id: id("se_3"),
    tenantId: "agency_palmcoast",
    source: "ai",
    message: "AI detected abandoned quote for Robert Jenkins. Marketing follow-up queued.",
    visibility: "internal",
    prospectId: "prospect_jenkins",
    createdAt: now(3),
  },
  {
    id: id("se_4"),
    tenantId: "agency_palmcoast",
    source: "customer",
    message: "Deposit of $1,000 paid toward yacht quote.",
    visibility: "customer_visible",
    customerId: "customer_demo",
    depositId: "deposit_yacht",
    createdAt: now(18),
  },
];

export const SEED_CAMPAIGNS: MarketingCampaign[] = [
  {
    id: id("camp_winterhome"),
    tenantId: "agency_palmcoast",
    name: "Coastal Winter Retention",
    channel: "email",
    audienceFilter: { assetType: "coastal_home", renewalWithinDays: 60 },
    status: "active",
    createdAt: now(40),
  },
  {
    id: id("camp_abandon"),
    tenantId: "agency_palmcoast",
    name: "Abandoned Quote Rescue",
    channel: "email",
    audienceFilter: { status: "abandoned" },
    status: "active",
    createdAt: now(60),
  },
];

export const SEED_MESSAGES: MarketingMessage[] = [
  {
    id: id("msg_jenkins_1"),
    tenantId: "agency_palmcoast",
    campaignId: "camp_abandon",
    prospectId: "prospect_jenkins",
    channel: "email",
    subject: "Wrapping up your Palm Beach home quote",
    content:
      "Hi Robert — I noticed you started a quote on your Palm Beach home but didn't finish. Most coastal homes here qualify for meaningful wind mitigation credits — happy to walk you through it on a 15-minute call this week.",
    sentAt: now(2),
    deliveryStatus: "opened",
    createdAt: now(2),
  },
];

export const SEED_RENEWALS: Renewal[] = [
  {
    id: id("ren_home"),
    tenantId: "agency_palmcoast",
    policyId: "policy_home",
    renewalDate: now(-305),
    status: "upcoming",
    agentId: "user_agent_pc",
    retentionActions: ["Send retention email", "Request updated wind mitigation"],
    createdAt: now(20),
  },
];

export const SEED_CLAIMS: Claim[] = [];

export const SEED_NOTES: Note[] = [
  {
    id: id("note_yacht"),
    tenantId: "agency_palmcoast",
    authorId: "user_agent_pc",
    customerId: "customer_demo",
    body: "Customer prefers SMS for quick updates. Captain credentials due Friday.",
    visibility: "internal",
    createdAt: now(10),
  },
];

export const SEED_COMMUNICATIONS: Communication[] = [
  {
    id: id("comm_1"),
    tenantId: "agency_palmcoast",
    customerId: "customer_demo",
    channel: "email",
    direction: "outbound",
    subject: "Welcome to Palm Coast Private Client",
    body: "Thank you for choosing us. Your dedicated agent is Olivia Marsh.",
    createdAt: now(89),
    createdById: "user_agent_pc",
  },
];

// =====================================================================
// Insurance categories — master-managed. The customer-facing quote flow
// reads from this table. `assetType` controls which built-in intake
// form renders; `questions[]` defines additional category-specific
// questions the schema renderer appends below the built-in fields.
//
// 30 of the most common categories private-client agencies write. The
// master portal can add/edit/remove categories and link/unlink them
// per agency (see SEED_CATEGORY_LINKS below).
// =====================================================================

// Reusable question fragments to keep the seed terse.
const Q = {
  estimatedValue: { key: "estimatedValue", label: "Estimated value (USD)", inputType: "currency" as const, required: true },
  address: { key: "address", label: "Primary address", inputType: "address" as const, required: true },
  garagingAddress: { key: "garagingAddress", label: "Garaging address", inputType: "address" as const, required: true },
  vin: { key: "vin", label: "VIN", inputType: "text" as const, placeholder: "17-character VIN", helpText: "Triggers NHTSA decoder for year/make/model." },
  year: { key: "year", label: "Year", inputType: "number" as const },
  make: { key: "make", label: "Make", inputType: "text" as const },
  model: { key: "model", label: "Model", inputType: "text" as const },
  notes: { key: "notes", label: "Additional notes", inputType: "textarea" as const },
};

export const SEED_CATEGORIES: InsuranceCategory[] = [
  // ---- Real estate (1–8) -------------------------------------------
  {
    id: "cat_primary_home", label: "Primary Home",
    description: "Owner-occupied principal residence.",
    assetType: "coastal_home", icon: "Home", active: true, sortOrder: 10, createdAt: now(360),
    questions: [
      Q.address, Q.estimatedValue,
      { key: "squareFootage", label: "Square footage", inputType: "number" },
      { key: "yearBuilt", label: "Year built", inputType: "number" },
      { key: "roofAge", label: "Roof age (years)", inputType: "number" },
      { key: "constructionType", label: "Construction type", inputType: "select", options: ["Concrete block","Frame","ICF","Steel frame","Other"] },
      { key: "occupancy", label: "Occupancy", inputType: "select", options: ["Year-round","Seasonal","Vacant >30d/yr"] },
    ],
  },
  {
    id: "cat_coastal_home", label: "Coastal / Beach Home",
    description: "Wind- and flood-exposed waterfront property.",
    assetType: "coastal_home", icon: "Home", active: true, sortOrder: 11, createdAt: now(360),
    questions: [
      Q.address, Q.estimatedValue,
      { key: "distanceToCoast", label: "Distance to coast (miles)", inputType: "number" },
      { key: "windMitigation", label: "Wind mitigation report on file?", inputType: "boolean" },
      { key: "floodZone", label: "Flood zone (FEMA)", inputType: "text", placeholder: "auto-filled from FEMA NFHL" },
      { key: "elevationCertificate", label: "Elevation certificate on file?", inputType: "boolean" },
      { key: "roofAge", label: "Roof age (years)", inputType: "number" },
    ],
  },
  {
    id: "cat_vacation_home", label: "Vacation Home",
    description: "Secondary residence — seasonal use.",
    assetType: "coastal_home", icon: "Home", active: true, sortOrder: 12, createdAt: now(360),
    questions: [
      Q.address, Q.estimatedValue,
      { key: "monthsOccupied", label: "Months occupied per year", inputType: "number" },
      { key: "caretaker", label: "Caretaker / property manager?", inputType: "boolean" },
      { key: "smartMonitoring", label: "24/7 leak / freeze monitoring?", inputType: "boolean" },
    ],
  },
  {
    id: "cat_rental_home", label: "Rental / Investment Property",
    description: "Tenant-occupied SFR or small multi-unit.",
    assetType: "coastal_home", icon: "Home", active: true, sortOrder: 13, createdAt: now(360),
    questions: [
      Q.address, Q.estimatedValue,
      { key: "monthlyRent", label: "Monthly rent (USD)", inputType: "currency" },
      { key: "leaseType", label: "Lease type", inputType: "select", options: ["Long-term (12mo+)","Short-term / Airbnb","Mid-term","Seasonal"] },
      { key: "tenantScreening", label: "Background checks on tenants?", inputType: "boolean" },
    ],
  },
  {
    id: "cat_condo", label: "Condo / Co-op",
    description: "HO-6 walls-in coverage for owner-occupied condos.",
    assetType: "coastal_home", icon: "Home", active: true, sortOrder: 14, createdAt: now(360),
    questions: [
      Q.address, Q.estimatedValue,
      { key: "hoaMasterPolicy", label: "HOA master policy type", inputType: "select", options: ["Bare walls","Single entity","All-in"] },
      { key: "lossAssessmentLimit", label: "Loss assessment limit needed (USD)", inputType: "currency" },
    ],
  },
  {
    id: "cat_estate", label: "Estate / Compound",
    description: "Multi-structure compound, >10k sqft main residence.",
    assetType: "coastal_home", icon: "Home", active: true, sortOrder: 15, createdAt: now(360),
    questions: [
      Q.address, Q.estimatedValue,
      { key: "outbuildings", label: "Number of outbuildings", inputType: "number" },
      { key: "guesthouseSqft", label: "Guesthouse square footage", inputType: "number" },
      { key: "securityStaff", label: "On-site security staff?", inputType: "boolean" },
    ],
  },
  {
    id: "cat_farm", label: "Farm / Ranch",
    description: "Working farm — barns, livestock, equipment.",
    assetType: "coastal_home", icon: "Home", active: true, sortOrder: 16, createdAt: now(360),
    questions: [
      Q.address, Q.estimatedValue,
      { key: "acreage", label: "Acreage", inputType: "number" },
      { key: "livestockValue", label: "Livestock value (USD)", inputType: "currency" },
      { key: "equipmentValue", label: "Equipment & machinery value (USD)", inputType: "currency" },
      { key: "commercialOperation", label: "Commercial farming operation?", inputType: "boolean" },
    ],
  },
  {
    id: "cat_vacant_land", label: "Vacant Land",
    description: "Undeveloped land — liability + limited property.",
    assetType: "coastal_home", icon: "Home", active: true, sortOrder: 17, createdAt: now(360),
    questions: [
      Q.address,
      { key: "acreage", label: "Acreage", inputType: "number" },
      { key: "publicAccess", label: "Public access permitted?", inputType: "boolean" },
    ],
  },

  // ---- Vehicles (9–14) ---------------------------------------------
  {
    id: "cat_luxury_vehicle", label: "Luxury Vehicle",
    description: "Premium daily drivers and exotics.",
    assetType: "luxury_vehicle", icon: "Briefcase", active: true, sortOrder: 20, createdAt: now(360),
    questions: [
      Q.vin, Q.year, Q.make, Q.model, Q.estimatedValue, Q.garagingAddress,
      { key: "usage", label: "Primary usage", inputType: "select", options: ["Pleasure","Commute","Collector"] },
      { key: "annualMileage", label: "Annual mileage", inputType: "number" },
    ],
  },
  {
    id: "cat_classic_car", label: "Classic / Collector Car",
    description: "Agreed-value coverage for vintage + show vehicles.",
    assetType: "luxury_vehicle", icon: "Briefcase", active: true, sortOrder: 21, createdAt: now(360),
    questions: [
      Q.year, Q.make, Q.model, Q.estimatedValue, Q.garagingAddress,
      { key: "agreedValue", label: "Requested agreed value (USD)", inputType: "currency", required: true },
      { key: "annualMileage", label: "Annual mileage (typically <5k)", inputType: "number" },
      { key: "storedClimate", label: "Climate-controlled garage?", inputType: "boolean" },
      { key: "appraisalOnFile", label: "Current appraisal on file?", inputType: "boolean" },
    ],
  },
  {
    id: "cat_standard_auto", label: "Standard Auto",
    description: "Family vehicles — sedans, SUVs, trucks.",
    assetType: "luxury_vehicle", icon: "Briefcase", active: true, sortOrder: 22, createdAt: now(360),
    questions: [
      Q.vin, Q.year, Q.make, Q.model, Q.estimatedValue, Q.garagingAddress,
      { key: "annualMileage", label: "Annual mileage", inputType: "number" },
      { key: "primaryDriver", label: "Primary driver name", inputType: "text" },
    ],
  },
  {
    id: "cat_motorcycle", label: "Motorcycle",
    description: "Touring, sport, cruiser bikes.",
    assetType: "luxury_vehicle", icon: "Briefcase", active: true, sortOrder: 23, createdAt: now(360),
    questions: [
      Q.year, Q.make, Q.model, Q.estimatedValue, Q.garagingAddress,
      { key: "engineDisplacement", label: "Engine displacement (cc)", inputType: "number" },
      { key: "msfCertified", label: "MSF safety course completed?", inputType: "boolean" },
    ],
  },
  {
    id: "cat_rv", label: "RV / Motorhome",
    description: "Class A/B/C motorhomes and travel trailers.",
    assetType: "luxury_vehicle", icon: "Briefcase", active: true, sortOrder: 24, createdAt: now(360),
    questions: [
      Q.year, Q.make, Q.model, Q.estimatedValue,
      { key: "rvClass", label: "RV class", inputType: "select", options: ["Class A","Class B","Class C","Travel trailer","Fifth wheel"] },
      { key: "fullTimeLiving", label: "Used as primary residence?", inputType: "boolean" },
    ],
  },
  {
    id: "cat_trailer", label: "Trailer / Camper",
    description: "Utility, horse, boat, and toy haulers.",
    assetType: "luxury_vehicle", icon: "Briefcase", active: true, sortOrder: 25, createdAt: now(360),
    questions: [
      Q.year, Q.make, Q.estimatedValue,
      { key: "trailerType", label: "Trailer type", inputType: "select", options: ["Utility","Boat","Horse","Toy hauler","Travel"] },
    ],
  },

  // ---- Marine (15–18) ----------------------------------------------
  {
    id: "cat_yacht", label: "Yacht",
    description: "Sailboats, motor yachts, charter vessels.",
    assetType: "yacht", icon: "Sailboat", active: true, sortOrder: 30, createdAt: now(360),
    questions: [
      Q.year, Q.make, Q.model, Q.estimatedValue,
      { key: "length", label: "Length (ft)", inputType: "number", required: true },
      { key: "navigationArea", label: "Cruising area", inputType: "text" },
      { key: "operator", label: "Operator", inputType: "select", options: ["Captain","Owner operated"] },
      { key: "marinaLocation", label: "Home marina", inputType: "address" },
    ],
  },
  {
    id: "cat_boat", label: "Boat",
    description: "Small craft, runabouts, sport fishers.",
    assetType: "yacht", icon: "Sailboat", active: true, sortOrder: 31, createdAt: now(360),
    questions: [
      Q.year, Q.make, Q.model, Q.estimatedValue,
      { key: "length", label: "Length (ft)", inputType: "number", required: true },
      { key: "hullType", label: "Hull type", inputType: "select", options: ["Fiberglass","Aluminum","Wood","Inflatable"] },
      { key: "horsepower", label: "Total horsepower", inputType: "number" },
    ],
  },
  {
    id: "cat_pwc", label: "Jet Ski / Personal Watercraft",
    description: "PWC and stand-up watercraft.",
    assetType: "yacht", icon: "Sailboat", active: true, sortOrder: 32, createdAt: now(360),
    questions: [
      Q.year, Q.make, Q.model, Q.estimatedValue,
      { key: "ridersHousehold", label: "Riders in household", inputType: "number" },
    ],
  },
  {
    id: "cat_dock", label: "Pier / Dock",
    description: "Private dock + lift coverage.",
    assetType: "yacht", icon: "Sailboat", active: true, sortOrder: 33, createdAt: now(360),
    questions: [
      Q.address, Q.estimatedValue,
      { key: "liftCapacity", label: "Boat lift capacity (lbs)", inputType: "number" },
      { key: "tidalExposure", label: "Tidal / hurricane exposure?", inputType: "boolean" },
    ],
  },

  // ---- Aviation (19–20) --------------------------------------------
  {
    id: "cat_aircraft", label: "Private Aircraft",
    description: "Single-engine, twin, turboprop, light jets.",
    assetType: "other", icon: "Sparkles", active: true, sortOrder: 40, createdAt: now(360),
    questions: [
      Q.year, Q.make, Q.model, Q.estimatedValue,
      { key: "tailNumber", label: "Tail number (N-number)", inputType: "text", required: true },
      { key: "pilotHours", label: "Pilot total flight hours", inputType: "number" },
      { key: "instrumentRated", label: "Instrument-rated pilot?", inputType: "boolean" },
      { key: "hangarLocation", label: "Hangar / base airport (ICAO)", inputType: "text" },
    ],
  },
  {
    id: "cat_drone", label: "Drone / UAV",
    description: "Hobbyist + commercial drones.",
    assetType: "other", icon: "Sparkles", active: true, sortOrder: 41, createdAt: now(360),
    questions: [
      Q.make, Q.model, Q.estimatedValue,
      { key: "part107", label: "FAA Part 107 certified?", inputType: "boolean" },
      { key: "commercialUse", label: "Commercial use?", inputType: "boolean" },
    ],
  },

  // ---- Personal property (21–25) -----------------------------------
  {
    id: "cat_jewelry", label: "Jewelry",
    description: "Scheduled rings, watches, necklaces.",
    assetType: "jewelry", icon: "Gem", active: true, sortOrder: 50, createdAt: now(360),
    questions: [
      Q.estimatedValue,
      { key: "itemType", label: "Item type", inputType: "text", placeholder: "Ring, watch, necklace…" },
      { key: "storage", label: "Storage", inputType: "select", options: ["Home safe","Bank vault","Worn frequently","Travel"] },
      { key: "wearFrequency", label: "Wear frequency", inputType: "select", options: ["Daily","Weekly","Special occasions","Never (stored)"] },
      { key: "appraisalDate", label: "Appraisal date", inputType: "date" },
    ],
  },
  {
    id: "cat_fine_art", label: "Fine Art Collection",
    description: "Paintings, sculpture, photography.",
    assetType: "jewelry", icon: "Gem", active: true, sortOrder: 51, createdAt: now(360),
    questions: [
      Q.estimatedValue,
      { key: "pieceCount", label: "Number of pieces", inputType: "number" },
      { key: "displayLocation", label: "Display location", inputType: "select", options: ["Primary home","Vacation home","Storage facility","Loaned to museum"] },
      { key: "climateControlled", label: "Climate-controlled environment?", inputType: "boolean" },
    ],
  },
  {
    id: "cat_wine", label: "Wine Collection",
    description: "Bottle counts, cellar value.",
    assetType: "jewelry", icon: "Gem", active: true, sortOrder: 52, createdAt: now(360),
    questions: [
      Q.estimatedValue,
      { key: "bottleCount", label: "Number of bottles", inputType: "number" },
      { key: "cellarLocation", label: "Cellar location", inputType: "select", options: ["At residence","Offsite wine storage"] },
      { key: "humidityMonitored", label: "Humidity + temp monitored?", inputType: "boolean" },
    ],
  },
  {
    id: "cat_watches", label: "Watch Collection",
    description: "Scheduled luxury timepieces.",
    assetType: "jewelry", icon: "Gem", active: true, sortOrder: 53, createdAt: now(360),
    questions: [
      Q.estimatedValue,
      { key: "watchCount", label: "Number of watches", inputType: "number" },
      { key: "storage", label: "Storage", inputType: "select", options: ["Home safe","Bank vault","Worn daily"] },
    ],
  },
  {
    id: "cat_furs", label: "Furs & Designer Goods",
    description: "Furs, handbags, couture.",
    assetType: "jewelry", icon: "Gem", active: true, sortOrder: 54, createdAt: now(360),
    questions: [
      Q.estimatedValue,
      { key: "itemCount", label: "Number of items", inputType: "number" },
      { key: "coldStorage", label: "Off-site cold storage?", inputType: "boolean" },
    ],
  },

  // ---- Liability (26–29) -------------------------------------------
  {
    id: "cat_umbrella", label: "Umbrella Liability",
    description: "Personal excess above auto + home.",
    assetType: "umbrella_liability", icon: "Umbrella", active: true, sortOrder: 60, createdAt: now(360),
    questions: [
      { key: "estimatedValue", label: "Limit requested (USD)", inputType: "currency", required: true },
      { key: "underlyingAuto", label: "Underlying auto BI limits", inputType: "select", options: ["250/500","500/500","500/1000","1000/1000"] },
      { key: "underlyingHome", label: "Underlying home liability limit (USD)", inputType: "currency" },
      { key: "youthfulDrivers", label: "Youthful drivers in household?", inputType: "boolean" },
    ],
  },
  {
    id: "cat_excess_liability", label: "Personal Excess Liability",
    description: "$5M+ excess for very high net worth.",
    assetType: "umbrella_liability", icon: "Umbrella", active: true, sortOrder: 61, createdAt: now(360),
    questions: [
      { key: "estimatedValue", label: "Limit requested (USD)", inputType: "currency", required: true },
      { key: "boardSeats", label: "Non-profit board seats", inputType: "number" },
      { key: "publicFigure", label: "Public figure / high media profile?", inputType: "boolean" },
    ],
  },
  {
    id: "cat_directors", label: "Directors & Officers (Personal)",
    description: "Personal D&O for non-profit / private-board service.",
    assetType: "umbrella_liability", icon: "Umbrella", active: true, sortOrder: 62, createdAt: now(360),
    questions: [
      { key: "estimatedValue", label: "Limit requested (USD)", inputType: "currency", required: true },
      { key: "boardSeats", label: "Board seats held", inputType: "number" },
      { key: "publiclyTraded", label: "Any publicly-traded company boards?", inputType: "boolean" },
    ],
  },
  {
    id: "cat_cyber", label: "Cyber / Identity Protection",
    description: "Personal cyber + identity restoration.",
    assetType: "umbrella_liability", icon: "Umbrella", active: true, sortOrder: 63, createdAt: now(360),
    questions: [
      { key: "estimatedValue", label: "Limit requested (USD)", inputType: "currency", required: true },
      { key: "householdSize", label: "Household size", inputType: "number" },
      { key: "highRiskOnline", label: "High-profile online presence?", inputType: "boolean" },
    ],
  },

  // ---- Special (30) ------------------------------------------------
  {
    id: "cat_full", label: "Full Portfolio",
    description: "Coordinated coverage across every asset.",
    assetType: "full_portfolio", icon: "Layers", active: true, sortOrder: 99, createdAt: now(360),
    questions: [
      Q.estimatedValue,
      Q.notes,
    ],
  },
];

// Default: link every category to every demo agency. Master can
// unlink categories per agency from the new master detail page.
const ALL_CATEGORY_IDS = SEED_CATEGORIES.map((c) => c.id);
export const SEED_CATEGORY_LINKS: CategoryAgencyLink[] = [
  ...ALL_CATEGORY_IDS.map((cid) => ({
    id: id(`catlink_pc_${cid}`),
    tenantId: "agency_palmcoast",
    categoryId: cid,
    active: true,
    createdAt: now(120),
  })),
  ...ALL_CATEGORY_IDS.map((cid) => ({
    id: id(`catlink_ls_${cid}`),
    tenantId: "agency_lakeshore",
    categoryId: cid,
    active: true,
    createdAt: now(300),
  })),
];