import { Download, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { useDemoNotice } from "@/lib/demo";
import { api } from "@/lib/api";
import { fmt } from "@/lib/format";
import type { Policy } from "@/types";

// =====================================================================
// Per-policy action group for the agent + manager portals.
//
//   - View policy     → navigates to /employee/policies/:id (full
//                       expandable detail page mirroring the customer
//                       portal's policy view: coverage, timeline,
//                       documents, asset back-link).
//   - Download policy → renders a plain-text policy summary and
//                       triggers a browser download. In production
//                       this swaps to the carrier's PDF endpoint.
//   - Edit policy     → opens the carrier's agent sign-in URL in a
//                       new tab (where the policy is actually
//                       editable). Falls back to a demo notice when
//                       the carrier doesn't have a published URL.
// =====================================================================

export function PolicyActions({
  policy,
  size = "sm",
}: {
  policy: Policy;
  size?: "sm" | "xs";
}) {
  const showDemoNotice = useDemoNotice();
  const customer = api.customers.get(policy.customerId);
  const asset = api.assets.get(policy.assetId);
  const carrier = api.carriers.get(policy.carrierId);

  function handleDownload() {
    const lines = buildPolicySummary({ policy, customerName: customer?.name, assetLabel: asset?.label, carrierName: carrier?.name });
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `policy-${fmt.policyRef(policy).replace(/[^a-z0-9-]/gi, "_")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function handleEdit() {
    if (carrier?.agentPortalUrl) {
      window.open(carrier.agentPortalUrl, "_blank", "noopener,noreferrer");
      return;
    }
    showDemoNotice({
      feature: "Edit policy on carrier site",
      title: `${carrier?.name ?? "Carrier"} agent portal not configured`,
      body: `In production, this opens ${carrier?.name ?? "the carrier"}'s agent sign-in for ${fmt.policyRef(policy)} so you can edit the policy directly on the carrier's system. Configure the carrier's agent portal URL under Master → Carriers to enable this link in the demo.`,
    });
  }

  return (
    <div className="flex items-center gap-1.5 flex-wrap justify-end">
      <Button
        size={size}
        to={`/employee/policies/${policy.id}`}
        title="View full policy details"
      >
        View
      </Button>
      <Button
        size={size}
        onClick={handleDownload}
        title="Download a policy summary"
        icon={<Download className="h-3.5 w-3.5" />}
      >
        Download
      </Button>
      <Button
        size={size}
        onClick={handleEdit}
        title={
          carrier?.agentPortalUrl
            ? `Open ${carrier.name}'s agent portal`
            : "Open carrier site (production deep-links to agent sign-in)"
        }
        icon={<ExternalLink className="h-3.5 w-3.5" />}
      >
        Edit on carrier
      </Button>
    </div>
  );
}

function buildPolicySummary(input: {
  policy: Policy;
  customerName?: string;
  assetLabel?: string;
  carrierName?: string;
}): string[] {
  const { policy: p, customerName, assetLabel, carrierName } = input;
  return [
    `POLICY SUMMARY`,
    `=============`,
    ``,
    `Policy number  : ${fmt.policyRef(p)}`,
    `Client         : ${customerName ?? "—"}`,
    `Asset          : ${assetLabel ?? "—"}`,
    `Carrier        : ${carrierName ?? "—"}`,
    `Status         : ${p.status}`,
    `Renewal status : ${p.renewalStatus}`,
    `Effective date : ${fmt.date(p.effectiveDate)}`,
    `Renewal date   : ${fmt.date(p.renewalDate)}`,
    `Premium est.   : ${p.premiumEstimate ? fmt.money(p.premiumEstimate) : "—"}`,
    `Final premium  : ${p.finalPremium ? fmt.money(p.finalPremium) : "—"}`,
    ``,
    `Generated by Quotex (demo). For an official carrier-issued PDF,`,
    `open this policy on the carrier's agent portal.`,
  ];
}